name: Andrew
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2089151
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E9E0CF'
    - '#302827'
    - '#99795B'
    - '#5C5C5C'
    - '#CE6E3A'
  brandStrength: 0.5
  lightness: 0.7631579
  saturation: 0.3281418
  rhythmicContrast: 0.4946294
purpose: []
