collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.3571429
  brandStrength: 0.556928
  lightness: 0.7137487
  brandColors:
    - '#0D0D0D'
    - '#BC8A5B'
    - '#6E4C38'
    - '#E0BDA3'
    - '#999B9A'
  rhythmicContrast: 0.6621912
typography_spectrum: 0.2089151
layout_spectrum: 0.4699248
name: Andrew
