collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3281418
  brandStrength: 0.7309344
  lightness: 0.7631579
  brandColors:
    - '#E9E0CF'
    - '#302827'
    - '#99795B'
    - '#5C5C5C'
    - '#CE6E3A'
  rhythmicContrast: 0.4946294
typography_spectrum: 0.2089151
layout_spectrum: 1
name: Andrew
