collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2153598
  lightness: 0.2443609
  brandStrength: 0.4172932
  brandColors:
    - '#0D0E0C'
    - '#76706C'
    - '#D09A80'
    - '#5C5529'
    - '#FFD8C6'
  rhythmicContrast: 1
typography_spectrum: 0.4688507
layout_spectrum: 0.170247
name: Andrew
